// Make embed.html, the copy of the tool that other sites place in a frame, from index.html.
// It is the same page with the title, explanation, questions and site footer cut away and
// a one-line credit added, so the two can never drift apart. A test fails if embed.html is
// out of date.  Usage: node tools/make-embed.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const CREDIT = `    <p class="embed-credit">
      <a href="https://polymend.xyz/" target="_blank" rel="noopener">Polymend</a>
      <a class="embed-badge" href="https://heyhaigh.ai/" target="_blank" rel="noopener" aria-label="Created by Ryan Haigh, heyhaigh.ai" title="Created by Ryan Haigh"><img src="app/ry-hand-badge-56.webp" srcset="app/ry-hand-badge-56.webp 2x, app/ry-hand-badge-84.webp 3x" alt="" width="28" height="28"></a>
    </p>`;

export function embedPage(home) {
  const replaceOnce = (text, from, to) => {
    if (text.split(from).length !== 2) throw new Error(`index.html should contain exactly one: ${from}`);
    return text.replace(from, to);
  };
  let page = home.replace(/[ \t]*<!-- embed:cut -->[\s\S]*?<!-- \/embed:cut -->\n/g, '');
  if (/embed:cut/.test(page)) throw new Error('index.html has an unmatched embed:cut marker');
  page = replaceOnce(page, '<!doctype html>\n', '<!doctype html>\n<!-- Made from index.html by tools/make-embed.mjs. Do not edit this file. -->\n');
  page = replaceOnce(page, '<html lang="en">', '<html lang="en" data-embed>');
  page = replaceOnce(page, '<body>', '<body class="embed">');
  page = page.replace(/<title>[^<]*<\/title>/, '<title>Polymend mesh repair</title>\n  <meta name="robots" content="noindex">');
  // Inside a frame, only the frame itself can take a dropped file.
  page = replaceOnce(page, 'Anywhere on this page works.', 'Anywhere in this box works.');
  page = replaceOnce(page, '    <!-- embed:credit -->', CREDIT);
  return page;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(root, 'embed.html'), embedPage(fs.readFileSync(path.join(root, 'index.html'), 'utf8')));
  console.log('embed.html written');
}
